categories:
  industrial_machinery:
    - "https://dir.indiamart.com/search.mp?ss=CNC%20Machine"
    - "https://dir.indiamart.com/search.mp?ss=Conveyor%20Belt"
  electronics:
    - "https://dir.indiamart.com/search.mp?ss=PCB%20Manufacturer"
    - "https://dir.indiamart.com/search.mp?ss=Power%20Supply"
  textiles:
    - "https://dir.indiamart.com/search.mp?ss=Fabric%20Roll"
    - "https://dir.indiamart.com/search.mp?ss=Yarn%20Supplier"
